language: python
python:
  - "3.6"

install:
  - pip install -r CardboardCube/requirements.txt
  - pip install coveralls

script: coverage run CardboardCube/manage.py test
notifications:
  email: false
after_success: coveralls
