# Generated by Django 2.2.7 on 2019-11-05 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('card_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubcollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_catalog.Card'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='collections',
            field=models.ManyToManyField(to='inventory.UserSubCollection'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='grading_details',
            field=models.ForeignKey(help_text='Details of card grade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.GradingDetails'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.UserInventory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
