# Generated by Django 2.2.7 on 2019-11-05 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('grading_service', models.CharField(choices=[('BGS', 'Beckett Grading Services'), ('BAS', 'Beckett Authentication Services'), ('PSA', 'Professional Sports Authentication')], max_length=32)),
                ('serial_number', models.CharField(max_length=12)),
                ('overall_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('autograph_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('centering_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('corners_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('edges_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('surfaces_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'grading_details',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('quantity_owned', models.IntegerField(default=0)),
                ('quantity_wanted', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], help_text='Card condition', max_length=3)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese Traditional'), ('ZH-S', 'Chinese Simplified'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('JA', 'Japanese'), ('KO', 'Korean'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ES', 'Spanish')], help_text='Card language?', max_length=4)),
                ('is_foil', models.BooleanField(default=False, help_text='Is the card foil?')),
                ('is_signed', models.BooleanField(default=False, help_text='Is the card signed?')),
                ('is_altered', models.BooleanField(default=False, help_text='Is the card altered?')),
                ('is_misprint', models.BooleanField(default=False, help_text='Is the card misprinted?')),
                ('is_miscut', models.BooleanField(default=False, help_text='Is the card miscut?')),
                ('is_graded', models.BooleanField(default=False, help_text='Is the card graded?')),
            ],
            options={
                'verbose_name': 'inventory_item',
                'verbose_name_plural': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubCollection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('CUBE', 'Cube'), ('DECK', 'Deck'), ('COLLECTION', 'Collection'), ('TRADELIST', 'Tradelist'), ('OTHER', 'Other')], max_length=10)),
                ('type_override', models.CharField(max_length=56)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
    ]
