# Generated by Django 3.0.5 on 2020-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200503_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='userinventory',
            name='inventory_items',
            field=models.ManyToManyField(to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='usersubcollection',
            name='inventory_items',
            field=models.ManyToManyField(to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='usersubcollection',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usersubcollection',
            name='kind',
            field=models.CharField(choices=[('CUBE', 'cube'), ('DECK', 'deck'), ('COLLECTION', 'collection'), ('TRADELIST', 'tradelist'), ('OTHER', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usersubcollection',
            name='kind_override',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
