# Generated by Django 2.2.7 on 2020-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200503_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', help_text='Card condition', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese Traditional'), ('ZH-S', 'Chinese Simplified'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('JA', 'Japanese'), ('KO', 'Korean'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ES', 'Spanish')], default='EN', help_text='Card language?', max_length=4),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_wanted',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
