# Generated by Django 3.0.5 on 2020-05-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200504_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingdetails',
            old_name='surfaces_grade',
            new_name='surface_grade',
        ),
    ]
