# Generated by Django 3.0.6 on 2020-05-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200504_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='usersubcollection',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, to='inventory.InventoryItem'),
        ),
    ]
